### ISSUE TITLE
A new Server has begun.

### ISSUE THREAD

**Issue by pacas00** [pacas00/exilemod-Server-mpmissions#1]
@SamuelFaith

check out Exile.Altis/config.cpp

push edits to the develop branch,

vanilla houses original files, master is the branch the server runs.

**Comment by Jacks0n05** [comment]
Hey thx for sharing can you write your Battleye filters ?

**Comment by pacas00** [comment]
We are just using the stock exilemod filters. The AI mod we added is Blckeagls' AI Mission. 

if your implementing it yourself, put 

`execVM "blckClient.sqf";` at the end of initPlayerLocal.sqf and

`if (isServer) then {
	execVM "\q\addons\custom_server\init.sqf";
};`  at the end of initServer.sqf

Good luck with your server mate.

http://epochmod.com/forum/index.php?/topic/30063-blckeagls-ai-mission-version-202-release-122015/

**Comment by pacas00** [comment]
closing this as it was intended as a notification to SamuelFaith.
